/**
 * Canonical Analysis Results for AbhedyaX Prototype.
 * Single source of truth for the 6 canonical scenario analyses.
 * Deterministic data matching Security Scoring Engine methodology.
 */

import { AnalysisResult } from "@/types/analysis";

export const CANONICAL_ANALYSIS_00428: AnalysisResult = {
  analysis_id: "AX-2026-00428",
  status: "completed",
  created_at: "2026-09-28T16:20:00Z",
  completed_at: "2026-09-28T16:20:08Z",
  engine_type: "simulation",
  source: {
    type: "simulation",
    name: "gw-delhi-hq-ipsec.pcap",
    file_name: "gw-delhi-hq-ipsec.pcap",
  },
  vpn: {
    protocol: "IPsec",
    ike_version: "IKEv2",
    mode: "Tunnel",
    ip_version: "IPv4",
    nat_traversal: true,
    protocols_detected: ["IKEv2", "ESP"],
  },
  cryptography: {
    encryption: "AES-256-GCM",
    authentication: "AEAD",
    dh_group: "DH Group 19",
    pfs: true,
  },
  security: {
    score: 100,
    grade: "A",
    risk_level: "Low",
    replay_protection: true,
    sa_lifetime_seconds: 28800,
  },
  risk_scoring: {
    base_score: 100,
    total_deduction: 0,
    security_score: 100,
    risk_level: "Low",
    scoring_breakdown: [],
    methodology_version: "v1.2.0-deterministic",
    formula: "score = max(0, 100 - sum(deductions))",
  },
  traffic: {
    predicted_class: "Video",
    traffic_class: "Video",
    confidence: 0.93,
    classification_mode: "simulated",
    candidate_classes: [
      { class: "Video", confidence: 0.93 },
      { class: "Web", confidence: 0.04 },
      { class: "Messaging", confidence: 0.03 },
    ],
    features: {
      mean_packet_size: 1142.5,
      median_packet_size: 1380.0,
      packet_size_p10: 92,
      packet_size_p90: 1420,
      flow_duration: 18.4,
      mean_inter_arrival_time: 0.0032,
      packet_rate: 312.4,
      direction_ratio: 0.84,
      burst_count: 14,
      burst_rate: 0.76,
      packet_size_pattern: "large_bursty",
      directionality: "bidirectional",
      session_duration_seconds: 842,
    },
    model: {
      name: "RandomForestClassifier",
      version: "v1.2.0",
    },
    explanation: [
      { feature: "mean_packet_size", value: 1142.5, importance: 0.38 },
      { feature: "mean_inter_arrival_time", value: 0.0032, importance: 0.28 },
      { feature: "direction_ratio", value: 0.84, importance: 0.18 },
      { feature: "burst_rate", value: 0.76, importance: 0.16 },
    ],
  },
  findings: [
    {
      id: "F-101",
      category: "Cryptography",
      severity: "Informational",
      title: "Compliant Authenticated Encryption Negotiated",
      description: "IPsec SA successfully established using AES-256-GCM AEAD cipher, meeting NIST SP 800-77 recommendations.",
      recommendation: "Maintain current cipher configuration.",
      evidence: ["Transform: ENCR_AES_GCM_16 (Key Length 256)", "No CBC mode detected"],
      confidence: 1.0,
    },
    {
      id: "F-102",
      category: "Key Exchange",
      severity: "Informational",
      title: "Strong Diffie-Hellman Group 19 (ECP-256)",
      description: "Diffie-Hellman Group 19 negotiated, providing ~128 bits of equivalent cryptographic security with elliptic curves.",
      recommendation: "Retain DH Group 19 or higher (Group 20/21).",
      evidence: ["Transform: DH_GROUP_19 (256-bit random ECP)"],
      confidence: 1.0,
    },
  ],
  summary: {
    total_findings: 2,
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    informational: 2,
  },
  evidence_provenance: [
    {
      id: "PROV-001",
      source_type: "Simulated",
      field: "vpn.protocol",
      value: "IKEv2",
      description: "Verified IPsec handshake protocol signature.",
      confidence: 1.0,
    },
    {
      id: "PROV-002",
      source_type: "Simulated",
      field: "cryptography.encryption",
      value: "AES-256-GCM",
      description: "Observed transform proposal in Security Association negotiation.",
      confidence: 1.0,
    },
    {
      id: "PROV-003",
      source_type: "Simulated",
      field: "cryptography.dh_group",
      value: "DH Group 19",
      description: "Diffie-Hellman group identified in key exchange payload.",
      confidence: 1.0,
    },
    {
      id: "PROV-004",
      source_type: "Simulated",
      field: "security.replay_protection",
      value: "true",
      description: "Anti-replay window status verified on active IPsec session.",
      confidence: 1.0,
    },
    {
      id: "PROV-005",
      source_type: "MLPrediction",
      field: "traffic.predicted_class",
      value: "Video",
      description: "Application class inferred from flow metadata patterns without payload decryption.",
      confidence: 0.93,
    },
  ],
  validation: {
    status: "passed",
    ground_truth_available: true,
    matched_fields: 6,
    total_fields: 6,
    mismatches: [],
  },
};

export const CANONICAL_ANALYSIS_00427: AnalysisResult = {
  analysis_id: "AX-2026-00427",
  status: "failed",
  created_at: "2026-09-28T15:45:00Z",
  completed_at: "2026-09-28T15:45:06Z",
  engine_type: "simulation",
  source: {
    type: "simulation",
    name: "legacy-branch-04.pcap",
    file_name: "legacy-branch-04.pcap",
  },
  vpn: {
    protocol: "IPsec",
    ike_version: "IKEv1",
    mode: "Tunnel",
    ip_version: "IPv4",
    nat_traversal: true,
    protocols_detected: ["IKEv1", "ESP"],
  },
  cryptography: {
    encryption: "AES-128-CBC",
    authentication: "HMAC-SHA1",
    dh_group: "DH Group 2",
    pfs: false,
  },
  security: {
    score: 25,
    grade: "F",
    risk_level: "Critical",
    replay_protection: false,
    sa_lifetime_seconds: 86400,
  },
  risk_scoring: {
    base_score: 100,
    total_deduction: 75,
    security_score: 25,
    risk_level: "Critical",
    scoring_breakdown: [
      {
        finding_id: "F-304",
        category: "Protocol",
        severity: "Critical",
        deduction: 25,
        reason: "RULE_DEPRECATED_IKE: IKEv1 protocol is deprecated by RFC 7296 and vulnerable to offline handshake interception.",
      },
      {
        finding_id: "F-301",
        category: "Key Exchange",
        severity: "Critical",
        deduction: 20,
        reason: "RULE_INSECURE_DH: Diffie-Hellman Group 2 (1024-bit MODP) provides <80 bits of equivalent security, vulnerable to precomputation attacks (Logjam).",
      },
      {
        finding_id: "F-302",
        category: "Cryptography",
        severity: "High",
        deduction: 15,
        reason: "RULE_WEAK_CRYPTO: AES-128-CBC cipher with HMAC-SHA1 lacks AEAD protection and is vulnerable to padding oracle attacks.",
      },
      {
        finding_id: "F-303",
        category: "Replay Protection",
        severity: "High",
        deduction: 15,
        reason: "RULE_ANTI_REPLAY_DISABLED: Replay protection is disabled on the active IPsec session, allowing packet duplicate injection.",
      },
    ],
    methodology_version: "v1.2.0-deterministic",
    formula: "score = max(0, 100 - sum(deductions))",
  },
  traffic: {
    predicted_class: "Messaging",
    traffic_class: "Messaging",
    confidence: 0.84,
    classification_mode: "simulated",
    candidate_classes: [
      { class: "Messaging", confidence: 0.84 },
      { class: "Web", confidence: 0.11 },
      { class: "Unknown", confidence: 0.05 },
    ],
    features: {
      mean_packet_size: 142.3,
      median_packet_size: 96.0,
      packet_size_p10: 64,
      packet_size_p90: 280,
      flow_duration: 45.2,
      mean_inter_arrival_time: 0.85,
      packet_rate: 1.4,
      direction_ratio: 0.52,
      burst_count: 8,
      burst_rate: 0.18,
      packet_size_pattern: "small_intermittent",
      directionality: "symmetric",
      session_duration_seconds: 310,
    },
    model: {
      name: "RandomForestClassifier",
      version: "v1.2.0",
    },
    explanation: [
      { feature: "mean_packet_size", value: 142.3, importance: 0.42 },
      { feature: "mean_inter_arrival_time", value: 0.85, importance: 0.31 },
      { feature: "packet_rate", value: 1.4, importance: 0.27 },
    ],
  },
  findings: [
    {
      id: "F-304",
      category: "Protocol",
      severity: "Critical",
      title: "Deprecated IKEv1 Protocol in Use",
      description: "The gateway uses IKEv1 which was formally deprecated by RFC 7296 and lacks modern anti-DDoS, exchange efficiency, and security features.",
      recommendation: "Migrate immediately to IKEv2 on all tunnel endpoints.",
      evidence: ["ISAKMP Major Version: 1", "Exchange Type: Identity Protection (Main Mode)"],
      confidence: 1.0,
    },
    {
      id: "F-301",
      category: "Key Exchange",
      severity: "Critical",
      title: "Insecure Diffie-Hellman Group 2 (1024-bit)",
      description: "Diffie-Hellman Group 2 provides only 1024-bit prime modulus, vulnerable to academic Logjam precomputation attacks.",
      recommendation: "Upgrade Diffie-Hellman group to Group 14 (2048-bit) minimum or Group 19/20 (ECP).",
      evidence: ["Transform Proposal: Group 2 (1024-bit MODP)"],
      confidence: 1.0,
    },
    {
      id: "F-302",
      category: "Cryptography",
      severity: "High",
      title: "Legacy AES-128-CBC with Deprecated HMAC-SHA1",
      description: "AES-128-CBC combined with HMAC-SHA1 integrity verification lacks authenticated encryption (AEAD) benefits.",
      recommendation: "Adopt AES-256-GCM or AES-128-GCM authenticated encryption.",
      evidence: ["Transform: AES-CBC (128-bit)", "Integrity: HMAC-SHA1-96"],
      confidence: 1.0,
    },
    {
      id: "F-303",
      category: "Replay Protection",
      severity: "High",
      title: "IPsec Anti-Replay Protection Disabled",
      description: "ESP sequence number verification window is disabled, leaving session open to packet re-injection and duplicate frame attacks.",
      recommendation: "Enable ESP anti-replay windowing (minimum 64-packet window, 128+ recommended).",
      evidence: ["Replay Window Size: 0 (Disabled)"],
      confidence: 1.0,
    },
  ],
  summary: {
    total_findings: 4,
    critical: 2,
    high: 2,
    medium: 0,
    low: 0,
    informational: 0,
  },
  evidence_provenance: [
    {
      id: "PROV-001",
      source_type: "Simulated",
      field: "vpn.protocol",
      value: "IKEv1",
      description: "Verified IPsec handshake protocol signature.",
      confidence: 1.0,
    },
    {
      id: "PROV-002",
      source_type: "Simulated",
      field: "cryptography.encryption",
      value: "AES-128-CBC",
      description: "Observed transform proposal in Security Association negotiation.",
      confidence: 1.0,
    },
    {
      id: "PROV-003",
      source_type: "Simulated",
      field: "cryptography.dh_group",
      value: "DH Group 2",
      description: "Diffie-Hellman group identified in key exchange payload.",
      confidence: 1.0,
    },
    {
      id: "PROV-004",
      source_type: "Simulated",
      field: "security.replay_protection",
      value: "false",
      description: "Anti-replay window status verified on active IPsec session.",
      confidence: 1.0,
    },
    {
      id: "PROV-005",
      source_type: "MLPrediction",
      field: "traffic.predicted_class",
      value: "Messaging",
      description: "Application class inferred from flow metadata patterns without payload decryption.",
      confidence: 0.84,
    },
  ],
  validation: {
    status: "passed",
    ground_truth_available: true,
    matched_fields: 6,
    total_fields: 6,
    mismatches: [],
  },
};

export const CANONICAL_ANALYSIS_00426: AnalysisResult = {
  analysis_id: "AX-2026-00426",
  status: "completed",
  created_at: "2026-09-28T14:10:00Z",
  completed_at: "2026-09-28T14:10:07Z",
  engine_type: "simulation",
  source: {
    type: "simulation",
    name: "dr-backup-link.pcap",
    file_name: "dr-backup-link.pcap",
  },
  vpn: {
    protocol: "IPsec",
    ike_version: "IKEv2",
    mode: "Tunnel",
    ip_version: "IPv4",
    nat_traversal: true,
    protocols_detected: ["IKEv2", "ESP"],
  },
  cryptography: {
    encryption: "AES-256-CBC",
    authentication: "HMAC-SHA256",
    dh_group: "DH Group 14",
    pfs: false,
  },
  security: {
    score: 80,
    grade: "B",
    risk_level: "Moderate",
    replay_protection: true,
    sa_lifetime_seconds: 86400,
  },
  risk_scoring: {
    base_score: 100,
    total_deduction: 20,
    security_score: 80,
    risk_level: "Moderate",
    scoring_breakdown: [
      {
        finding_id: "F-201",
        category: "PFS",
        severity: "Medium",
        deduction: 12,
        reason: "RULE_NO_PFS: Perfect Forward Secrecy is disabled on Child SA, allowing historical retrospective decryption if Phase 1 key is compromised.",
      },
      {
        finding_id: "F-202",
        category: "Configuration",
        severity: "Low",
        deduction: 8,
        reason: "RULE_EXTENDED_SA_LIFETIME: Configured SA lifetime (86400s / 24h) exceeds NIST SP 800-77 recommended 8-hour maximum.",
      },
    ],
    methodology_version: "v1.2.0-deterministic",
    formula: "score = max(0, 100 - sum(deductions))",
  },
  traffic: {
    predicted_class: "Web",
    traffic_class: "Web",
    confidence: 0.89,
    classification_mode: "simulated",
    candidate_classes: [
      { class: "Web", confidence: 0.89 },
      { class: "Video", confidence: 0.08 },
      { class: "Unknown", confidence: 0.03 },
    ],
    features: {
      mean_packet_size: 684.2,
      median_packet_size: 512.0,
      packet_size_p10: 74,
      packet_size_p90: 1350,
      flow_duration: 32.1,
      mean_inter_arrival_time: 0.045,
      packet_rate: 68.2,
      direction_ratio: 0.68,
      burst_count: 11,
      burst_rate: 0.34,
      packet_size_pattern: "moderate_request_response",
      directionality: "asymmetric_download",
      session_duration_seconds: 420,
    },
    model: {
      name: "RandomForestClassifier",
      version: "v1.2.0",
    },
    explanation: [
      { feature: "mean_packet_size", value: 684.2, importance: 0.35 },
      { feature: "direction_ratio", value: 0.68, importance: 0.30 },
      { feature: "burst_rate", value: 0.34, importance: 0.20 },
    ],
  },
  findings: [
    {
      id: "F-201",
      category: "PFS",
      severity: "Medium",
      title: "Perfect Forward Secrecy (PFS) Disabled",
      description: "Child SA does not perform a fresh Diffie-Hellman exchange during rekeying, linking data keys to the initial IKE SA master secret.",
      recommendation: "Enable PFS (pfs=yes) on Phase 2 Child SA proposals.",
      evidence: ["Child SA Proposal: No KE payload present"],
      confidence: 1.0,
    },
    {
      id: "F-202",
      category: "Configuration",
      severity: "Low",
      title: "Extended SA Lifetime (24 Hours)",
      description: "Security Association lifetime configured to 86400 seconds (24h), expanding the operational cryptoperiod window beyond NIST SP 800-77 recommendations (8h).",
      recommendation: "Reduce SA lifetime to 28800 seconds (8 hours) or 4 hours for high-volume gateways.",
      evidence: ["SA Duration: 86400 seconds (24.0 hours)"],
      confidence: 1.0,
    },
  ],
  summary: {
    total_findings: 2,
    critical: 0,
    high: 0,
    medium: 1,
    low: 1,
    informational: 0,
  },
  evidence_provenance: [
    {
      id: "PROV-001",
      source_type: "Simulated",
      field: "vpn.protocol",
      value: "IKEv2",
      description: "Verified IPsec handshake protocol signature.",
      confidence: 1.0,
    },
    {
      id: "PROV-002",
      source_type: "Simulated",
      field: "cryptography.encryption",
      value: "AES-256-CBC",
      description: "Observed transform proposal in Security Association negotiation.",
      confidence: 1.0,
    },
    {
      id: "PROV-003",
      source_type: "Simulated",
      field: "cryptography.dh_group",
      value: "DH Group 14",
      description: "Diffie-Hellman group identified in key exchange payload.",
      confidence: 1.0,
    },
    {
      id: "PROV-004",
      source_type: "Simulated",
      field: "security.replay_protection",
      value: "true",
      description: "Anti-replay window status verified on active IPsec session.",
      confidence: 1.0,
    },
    {
      id: "PROV-005",
      source_type: "MLPrediction",
      field: "traffic.predicted_class",
      value: "Web",
      description: "Application class inferred from flow metadata patterns without payload decryption.",
      confidence: 0.89,
    },
  ],
  validation: {
    status: "passed",
    ground_truth_available: true,
    matched_fields: 6,
    total_fields: 6,
    mismatches: [],
  },
};

export const CANONICAL_ANALYSIS_00425: AnalysisResult = {
  analysis_id: "AX-2026-00425",
  status: "completed",
  created_at: "2026-09-28T12:35:00Z",
  completed_at: "2026-09-28T12:35:06Z",
  engine_type: "simulation",
  source: {
    type: "simulation",
    name: "cloud-gw-ipv6.pcap",
    file_name: "cloud-gw-ipv6.pcap",
  },
  vpn: {
    protocol: "IPsec",
    ike_version: "IKEv2",
    mode: "Tunnel",
    ip_version: "IPv6",
    nat_traversal: false,
    protocols_detected: ["IKEv2", "ESP"],
  },
  cryptography: {
    encryption: "AES-256-GCM",
    authentication: "AEAD",
    dh_group: "DH Group 20",
    pfs: true,
  },
  security: {
    score: 100,
    grade: "A",
    risk_level: "Low",
    replay_protection: true,
    sa_lifetime_seconds: 28800,
  },
  risk_scoring: {
    base_score: 100,
    total_deduction: 0,
    security_score: 100,
    risk_level: "Low",
    scoring_breakdown: [],
    methodology_version: "v1.2.0-deterministic",
    formula: "score = max(0, 100 - sum(deductions))",
  },
  traffic: {
    predicted_class: "VoIP",
    traffic_class: "VoIP",
    confidence: 0.91,
    classification_mode: "simulated",
    candidate_classes: [
      { class: "VoIP", confidence: 0.91 },
      { class: "Video", confidence: 0.06 },
      { class: "Web", confidence: 0.03 },
    ],
    features: {
      mean_packet_size: 218.4,
      median_packet_size: 210.0,
      packet_size_p10: 190,
      packet_size_p90: 250,
      flow_duration: 60.0,
      mean_inter_arrival_time: 0.0201,
      packet_rate: 49.8,
      direction_ratio: 0.98,
      burst_count: 2,
      burst_rate: 0.03,
      packet_size_pattern: "fixed_codec_frames",
      directionality: "symmetric_realtime",
      session_duration_seconds: 960,
    },
    model: {
      name: "RandomForestClassifier",
      version: "v1.2.0",
    },
    explanation: [
      { feature: "mean_inter_arrival_time", value: 0.0201, importance: 0.44 },
      { feature: "mean_packet_size", value: 218.4, importance: 0.36 },
      { feature: "direction_ratio", value: 0.98, importance: 0.20 },
    ],
  },
  findings: [
    {
      id: "F-501",
      category: "Cryptography",
      severity: "Informational",
      title: "CNSA Suite B Cryptography Verified",
      description: "Diffie-Hellman Group 20 (384-bit ECP) and AES-256-GCM fulfill CNSA Suite B requirements for classified network communication.",
      recommendation: "Maintain high-assurance cryptographic profile.",
      evidence: ["DH Group 20 (ECP-384)", "AES-GCM-256 authenticated encryption"],
      confidence: 1.0,
    },
  ],
  summary: {
    total_findings: 1,
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    informational: 1,
  },
  evidence_provenance: [
    {
      id: "PROV-001",
      source_type: "Simulated",
      field: "vpn.protocol",
      value: "IKEv2",
      description: "Verified native IPv6 IPsec handshake.",
      confidence: 1.0,
    },
    {
      id: "PROV-002",
      source_type: "Simulated",
      field: "cryptography.encryption",
      value: "AES-256-GCM",
      description: "Observed transform proposal in Security Association negotiation.",
      confidence: 1.0,
    },
    {
      id: "PROV-003",
      source_type: "Simulated",
      field: "cryptography.dh_group",
      value: "DH Group 20",
      description: "Diffie-Hellman Group 20 (384-bit ECP) identified in key exchange payload.",
      confidence: 1.0,
    },
  ],
  validation: {
    status: "passed",
    ground_truth_available: true,
    matched_fields: 6,
    total_fields: 6,
    mismatches: [],
  },
};

export const CANONICAL_ANALYSIS_00424: AnalysisResult = {
  analysis_id: "AX-2026-00424",
  status: "completed",
  created_at: "2026-09-28T11:05:00Z",
  completed_at: "2026-09-28T11:05:07Z",
  engine_type: "simulation",
  source: {
    type: "simulation",
    name: "perimeter-tap-anomaly.pcap",
    file_name: "perimeter-tap-anomaly.pcap",
  },
  vpn: {
    protocol: "IPsec",
    ike_version: "IKEv2",
    mode: "Tunnel",
    ip_version: "IPv4",
    nat_traversal: true,
    protocols_detected: ["IKEv2", "ESP"],
  },
  cryptography: {
    encryption: "AES-256-GCM",
    authentication: "AEAD",
    dh_group: "DH Group 19",
    pfs: true,
  },
  security: {
    score: 95,
    grade: "A",
    risk_level: "Low",
    replay_protection: true,
    sa_lifetime_seconds: 28800,
  },
  risk_scoring: {
    base_score: 100,
    total_deduction: 5,
    security_score: 95,
    risk_level: "Low",
    scoring_breakdown: [
      {
        finding_id: "F-401",
        category: "Metadata Exposure",
        severity: "Low",
        deduction: 5,
        reason: "RULE_TRAFFIC_ANOMALY: Burst regularity and low-entropy timing indicate synthetic exfiltration or tunnel side-channel divergence.",
      },
    ],
    methodology_version: "v1.2.0-deterministic",
    formula: "score = max(0, 100 - sum(deductions))",
  },
  traffic: {
    predicted_class: "Unknown",
    traffic_class: "Unknown",
    confidence: 0.61,
    classification_mode: "simulated",
    candidate_classes: [
      { class: "Unknown", confidence: 0.61 },
      { class: "Web", confidence: 0.22 },
      { class: "Video", confidence: 0.17 },
    ],
    features: {
      mean_packet_size: 924.1,
      median_packet_size: 910.0,
      packet_size_p10: 890,
      packet_size_p90: 960,
      flow_duration: 120.0,
      mean_inter_arrival_time: 0.0102,
      packet_rate: 98.1,
      direction_ratio: 0.96,
      burst_count: 42,
      burst_rate: 0.35,
      packet_size_pattern: "synthetic_fixed_length",
      directionality: "unidirectional_upload",
      session_duration_seconds: 120,
    },
    model: {
      name: "RandomForestClassifier",
      version: "v1.2.0",
    },
    explanation: [
      { feature: "packet_size_p90", value: 960, importance: 0.40 },
      { feature: "burst_count", value: 42, importance: 0.35 },
      { feature: "direction_ratio", value: 0.96, importance: 0.25 },
    ],
  },
  findings: [
    {
      id: "F-401",
      category: "Metadata Exposure",
      severity: "Low",
      title: "Encrypted Side-Channel Burst Anomaly Detected",
      description: "Observed packet length variance and strict pacing deviate from typical interactive human traffic models, reflecting programmatic or automated exfiltration activity.",
      recommendation: "Correlate tunnel flow timestamps with host application telemetry and firewall egress logs.",
      evidence: ["Inter-arrival variance < 0.001s", "Packet size kurtosis: 4.8"],
      confidence: 0.88,
    },
  ],
  summary: {
    total_findings: 1,
    critical: 0,
    high: 0,
    medium: 0,
    low: 1,
    informational: 0,
  },
  evidence_provenance: [
    {
      id: "PROV-001",
      source_type: "Simulated",
      field: "vpn.protocol",
      value: "IKEv2",
      description: "Verified IPsec handshake protocol signature.",
      confidence: 1.0,
    },
    {
      id: "PROV-002",
      source_type: "MLPrediction",
      field: "traffic.predicted_class",
      value: "Unknown",
      description: "Application class abstained to Unknown due to flow feature anomaly.",
      confidence: 0.61,
    },
  ],
  validation: {
    status: "passed",
    ground_truth_available: true,
    matched_fields: 6,
    total_fields: 6,
    mismatches: [],
  },
};

export const CANONICAL_ANALYSIS_00423: AnalysisResult = {
  analysis_id: "AX-2026-00423",
  status: "completed",
  created_at: "2026-09-28T09:15:00Z",
  completed_at: "2026-09-28T09:15:05Z",
  engine_type: "real",
  source: {
    type: "pcap",
    name: "remote-worker-gateway.pcap",
    file_name: "remote-worker-gateway.pcap",
  },
  vpn: {
    protocol: "IKEv2",
    ike_version: "IKEv2",
    mode: "Tunnel",
    ip_version: "IPv4",
    nat_traversal: true,
    protocols_detected: ["IKEv2", "ESP"],
  },
  cryptography: {
    encryption: "ChaCha20-Poly1305",
    authentication: "AEAD",
    dh_group: "DH Group 19",
    pfs: true,
  },
  security: {
    score: 100,
    grade: "A",
    risk_level: "Low",
    replay_protection: true,
    sa_lifetime_seconds: 28800,
  },
  risk_scoring: {
    base_score: 100,
    total_deduction: 0,
    security_score: 100,
    risk_level: "Low",
    scoring_breakdown: [],
    methodology_version: "v1.2.0-deterministic",
    formula: "score = max(0, 100 - sum(deductions))",
  },
  traffic: {
    predicted_class: "Web",
    traffic_class: "Web",
    confidence: 0.91,
    classification_mode: "ml",
    candidate_classes: [
      { class: "Web", confidence: 0.91 },
      { class: "Video", confidence: 0.05 },
      { class: "Messaging", confidence: 0.04 },
    ],
    features: {
      mean_packet_size: 580.4,
      median_packet_size: 490.0,
      packet_size_p10: 84,
      packet_size_p90: 1280,
      flow_duration: 25.4,
      mean_inter_arrival_time: 0.038,
      packet_rate: 84.1,
      direction_ratio: 0.72,
      burst_count: 9,
      burst_rate: 0.35,
      packet_size_pattern: "https_web_browsing",
      directionality: "client_server_requests",
      session_duration_seconds: 340,
    },
    model: {
      name: "RandomForestClassifier",
      version: "v1.2.0",
    },
    explanation: [
      { feature: "mean_packet_size", value: 580.4, importance: 0.38 },
      { feature: "direction_ratio", value: 0.72, importance: 0.32 },
    ],
  },
  findings: [
    {
      id: "F-601",
      category: "Cryptography",
      severity: "Informational",
      title: "ChaCha20-Poly1305 Modern AEAD In Use",
      description: "Tunnel negotiated RFC 7634 ChaCha20-Poly1305 authenticated encryption, optimal for devices lacking hardware AES acceleration.",
      recommendation: "Maintain approved modern AEAD ciphers.",
      evidence: ["Transform: CHACHA20_POLY1305 (256-bit)"],
      confidence: 1.0,
    },
  ],
  summary: {
    total_findings: 1,
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    informational: 1,
  },
  evidence_provenance: [
    {
      id: "PROV-001",
      source_type: "Observed",
      field: "vpn.protocol",
      value: "IKEv2",
      description: "Wire dissected packet headers from PCAP capture.",
      confidence: 1.0,
    },
  ],
  validation: {
    status: "passed",
    ground_truth_available: true,
    matched_fields: 6,
    total_fields: 6,
    mismatches: [],
  },
};

export const CANONICAL_ANALYSES_MAP: Record<string, AnalysisResult> = {
  "AX-2026-00428": CANONICAL_ANALYSIS_00428,
  "AX-2026-00427": CANONICAL_ANALYSIS_00427,
  "AX-2026-00426": CANONICAL_ANALYSIS_00426,
  "AX-2026-00425": CANONICAL_ANALYSIS_00425,
  "AX-2026-00424": CANONICAL_ANALYSIS_00424,
  "AX-2026-00423": CANONICAL_ANALYSIS_00423,
};

export const CANONICAL_ANALYSES_LIST: AnalysisResult[] = [
  CANONICAL_ANALYSIS_00428,
  CANONICAL_ANALYSIS_00427,
  CANONICAL_ANALYSIS_00426,
  CANONICAL_ANALYSIS_00425,
  CANONICAL_ANALYSIS_00424,
  CANONICAL_ANALYSIS_00423,
];
