"""strongSwan configuration generator for both swanctl (VICI) and ipsec.conf styles."""

from typing import Dict, Tuple
from services.testbed.src.scenarios.models import ScenarioDefinition

# DH group mappings to strongSwan keyword identifiers
DH_GROUP_MAP: Dict[str, str] = {
    "DH Group 1": "modp768",
    "DH Group 2": "modp1024",
    "DH Group 5": "modp1536",
    "DH Group 14": "modp2048",
    "DH Group 15": "modp3072",
    "DH Group 16": "modp4096",
    "DH Group 19": "ecp256",
    "DH Group 20": "ecp384",
    "DH Group 21": "ecp521",
}

# Cipher mappings to strongSwan cipher identifiers
CIPHER_MAP: Dict[str, str] = {
    "AES-256-GCM": "aes256gcm16",
    "AES-128-GCM": "aes128gcm16",
    "AES-256-CBC": "aes256",
    "AES-128-CBC": "aes128",
    "3DES": "3des",
    "DES": "des",
}

# Integrity algorithm mappings
INTEG_MAP: Dict[str, str] = {
    "AEAD": "",
    "HMAC-SHA512": "sha512",
    "HMAC-SHA384": "sha384",
    "HMAC-SHA256": "sha256",
    "HMAC-SHA1": "sha1",
    "HMAC-MD5": "md5",
}


def build_proposals(scenario: ScenarioDefinition) -> Tuple[str, str]:
    """
    Construct IKE and ESP proposal strings compatible with strongSwan.
    Returns (ike_proposal, esp_proposal).
    """
    cipher = CIPHER_MAP.get(scenario.encryption, scenario.encryption.lower().replace("-", ""))
    dh = DH_GROUP_MAP.get(scenario.dh_group, "modp2048")
    integ = INTEG_MAP.get(scenario.authentication, "sha256")

    is_aead = "gcm" in cipher.lower()

    # 1. IKE Proposal
    if is_aead:
        # For IKE SA in IKEv2, AEAD uses prf
        ike_prop = f"{cipher}-prfsha256-{dh}"
    else:
        ike_prop = f"{cipher}-{integ}-{dh}"

    # 2. ESP Proposal (Child SA)
    if is_aead:
        esp_prop = f"{cipher}"
    else:
        esp_prop = f"{cipher}-{integ}"

    if scenario.pfs:
        esp_prop = f"{esp_prop}-{dh}"

    return ike_prop, esp_prop


def generate_swanctl_conf(scenario: ScenarioDefinition, is_initiator: bool = True) -> str:
    """Generate modern swanctl.conf formatted configuration."""
    ike_prop, esp_prop = build_proposals(scenario)
    version_num = "2" if scenario.ike_version == "IKEv2" else "1"
    mode_str = "tunnel" if scenario.mode == "Tunnel" else "transport"
    replay_window = 32 if scenario.replay_protection else 0
    rekey_time = f"{int(scenario.sa_lifetime_seconds * 0.9)}s"
    lifetime = f"{scenario.sa_lifetime_seconds}s"

    local_ip = "192.168.10.2" if is_initiator else "192.168.20.2"
    remote_ip = "192.168.20.2" if is_initiator else "192.168.10.2"
    local_ts = "10.100.1.0/24" if is_initiator else "10.100.2.0/24"
    remote_ts = "10.100.2.0/24" if is_initiator else "10.100.1.0/24"

    if scenario.ip_version == "IPv6":
        local_ip = "fd00:10::2" if is_initiator else "fd00:20::2"
        remote_ip = "fd00:20::2" if is_initiator else "fd00:10::2"
        local_ts = "fd00:100:1::/64" if is_initiator else "fd00:100:2::/64"
        remote_ts = "fd00:100:2::/64" if is_initiator else "fd00:100:1::/64"

    start_action = "start" if is_initiator else "none"

    return f"""# Generated by AbhedyaX Testbed Orchestrator
# Scenario: {scenario.scenario_id} ({scenario.name})
# IKE Version: {scenario.ike_version} | Mode: {scenario.mode}

connections {{
    {scenario.scenario_id} {{
        version = {version_num}
        local_addrs = {local_ip}
        remote_addrs = {remote_ip}
        proposals = {ike_prop}
        rekey_time = {rekey_time}

        local {{
            auth = psk
            id = {"client@abhedyax.internal" if is_initiator else "gateway@abhedyax.internal"}
        }}
        remote {{
            auth = psk
            id = {"gateway@abhedyax.internal" if is_initiator else "client@abhedyax.internal"}
        }}

        children {{
            {scenario.scenario_id}-child {{
                mode = {mode_str}
                esp_proposals = {esp_prop}
                local_ts = {local_ts}
                remote_ts = {remote_ts}
                rekey_time = {rekey_time}
                life_time = {lifetime}
                replay_window = {replay_window}
                start_action = {start_action}
            }}
        }}
    }}
}}

secrets {{
    ike-abhedyax {{
        id-client = client@abhedyax.internal
        id-gw = gateway@abhedyax.internal
        secret = "AbhedyaX-Deterministic-Testbed-Secret-2026!"
    }}
}}
"""


def generate_ipsec_conf(scenario: ScenarioDefinition, is_initiator: bool = True) -> str:
    """Generate legacy ipsec.conf formatted configuration."""
    ike_prop, esp_prop = build_proposals(scenario)
    version_key = "ikev2" if scenario.ike_version == "IKEv2" else "ikev1"
    mode_str = "tunnel" if scenario.mode == "Tunnel" else "transport"
    auto_action = "start" if is_initiator else "add"

    left_ip = "192.168.10.2" if is_initiator else "192.168.20.2"
    right_ip = "192.168.20.2" if is_initiator else "192.168.10.2"
    left_subnet = "10.100.1.0/24" if is_initiator else "10.100.2.0/24"
    right_subnet = "10.100.2.0/24" if is_initiator else "10.100.1.0/24"

    if scenario.ip_version == "IPv6":
        left_ip = "fd00:10::2" if is_initiator else "fd00:20::2"
        right_ip = "fd00:20::2" if is_initiator else "fd00:10::2"
        left_subnet = "fd00:100:1::/64" if is_initiator else "fd00:100:2::/64"
        right_subnet = "fd00:100:2::/64" if is_initiator else "fd00:100:1::/64"

    pfs_val = "yes" if scenario.pfs else "no"
    replay_window = 32 if scenario.replay_protection else 0

    return f"""# Generated by AbhedyaX Testbed Orchestrator
# Scenario: {scenario.scenario_id} - Classic ipsec.conf

config setup
    charondebug="ike 2, knl 2, cfg 2, esp 2"

conn {scenario.scenario_id}
    keyexchange={version_key}
    type={mode_str}
    authby=secret
    left={left_ip}
    leftid={"client@abhedyax.internal" if is_initiator else "gateway@abhedyax.internal"}
    leftsubnet={left_subnet}
    right={right_ip}
    rightid={"gateway@abhedyax.internal" if is_initiator else "client@abhedyax.internal"}
    rightsubnet={right_subnet}
    ike={ike_prop}
    esp={esp_prop}
    pfs={pfs_val}
    lifetime={scenario.sa_lifetime_seconds}s
    replay_window={replay_window}
    auto={auto_action}
"""
